kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: dobs.csi.digitalocean.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
